# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SafeAirDevice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Firestore'

pod 'Charts'
pod 'TinyConstraints'


  # Pods for SafeAirDevice

end
